### PR TITLE
Prettyprinter fixes

### PR DESCRIPTION
**Pull request by domenkozar**
Before:

```
let
  localLib = import ./lib.nix;
  in { compiler ? pkgs.haskell.packages.ghc802, config ? {}, enableDebugging ? false, enableProfiling ? false, pkgs ? import localLib.fetchNixPkgs {
    inherit system config;
  }, system ? builtins.currentSystem }:
  with pkgs.lib; with pkgs.haskell.lib; let
      nixops = let
        nixopsUnstable = pkgs.fetchFromGitHub {
          owner = "NixOS";
          repo = "nixops";
          rev = "92034401b5291070a93ede030e718bb82b5e6da4";
          sha256 = "139mmf8ag392w5mn419k7ajp3pgcz6q349n7vm7gsp3g4sck2jjn";
        };
        in (import "${nixopsUnstable}/release.nix" {
          nixpkgs = localLib.fetchNixPkgs;
        }).build.system;
      iohk-ops-extra-runtime-deps = [
        pkgs.gitFull
        pkgs.nix-prefetch-scripts
        compiler.yaml
        pkgs.wget
        pkgs.file
        cardano-sl-pkgs.cardano-sl-auxx
        cardano-sl-pkgs.cardano-sl-tools
        nixops
        pkgs.terraform_0_11
      ];
      cardano-sl-src = builtins.fromJSON (builtins.readFile ./cardano-sl-src.json);
      cardano-sl-pkgs = import (pkgs.fetchgit cardano-sl-src) {
        gitrev = cardano-sl-src.rev;
        inherit enableDebugging
        enableProfiling;
      };
      in {
        inherit nixops;
        iohk-ops = pkgs.haskell.lib.overrideCabal (compiler.callPackage ./iohk/default.nix {}) (drv:
        {
            executableToolDepends = [
              pkgs.makeWrapper
            ];
            libraryHaskellDepends = iohk-ops-extra-runtime-deps;
            postInstall = ''
              wrapProgram ''$out/bin/iohk-ops \
              --prefix PATH : "${pkgs.lib.makeBinPath iohk-ops-extra-runtime-deps}"
            '';
          });
      } // cardano-sl-pkgs

```

after:

```
let
  localLib = import ./lib.nix;
in { compiler ? pkgs.haskell.packages.ghc802
   , config ? {}
   , enableDebugging ? false
   , enableProfiling ? false
   , pkgs ? import localLib.fetchNixPkgs {
     inherit system config;
   }
   , system ? builtins.currentSystem}:
  with pkgs.lib;
  with pkgs.haskell.lib;
  let
    nixops = let
      nixopsUnstable = pkgs.fetchFromGitHub {
        owner = "NixOS";
        repo = "nixops";
        rev = "92034401b5291070a93ede030e718bb82b5e6da4";
        sha256 = "139mmf8ag392w5mn419k7ajp3pgcz6q349n7vm7gsp3g4sck2jjn";
      };
    in (import "${nixopsUnstable}/release.nix" {
      nixpkgs = localLib.fetchNixPkgs;
    }).build.system;
    iohk-ops-extra-runtime-deps = [
      pkgs.gitFull
      pkgs.nix-prefetch-scripts
      compiler.yaml
      pkgs.wget
      pkgs.file
      cardano-sl-pkgs.cardano-sl-auxx
      cardano-sl-pkgs.cardano-sl-tools
      nixops
      pkgs.terraform_0_11
    ];
    cardano-sl-src = builtins.fromJSON (builtins.readFile ./cardano-sl-src.json);
    cardano-sl-pkgs = import (pkgs.fetchgit cardano-sl-src) {
      gitrev = cardano-sl-src.rev;
      inherit enableDebugging
      enableProfiling;
    };
  in {
    inherit nixops;
    iohk-ops = pkgs.haskell.lib.overrideCabal (compiler.callPackage ./iohk/default.nix {}) (drv:
      {
        executableToolDepends = [
          pkgs.makeWrapper
        ];
        libraryHaskellDepends = iohk-ops-extra-runtime-deps;
        postInstall = ''
          wrapProgram $out/bin/iohk-ops \
          --prefix PATH : "${pkgs.lib.makeBinPath iohk-ops-extra-runtime-deps}"
        '';
      });
  } // cardano-sl-pkgs
```

@jwiegley

### CODE REVIEW

**Comment by bennofs** [comment]
Great! I wonder if it would make sense to format arglists following `in` like this instead:

```
let
  ...
in 
  { a
  , b
  , ...
  }:
```

It would avoid the need for an indent level that is not a multiple of the basic indent (2 spaces).

**Comment by domenkozar** [comment]
@bennofs that's where it gets tricky, trading vertical for horizontal space. I guess extra space is more precious.

**Comment by domenkozar** [comment]
@jwiegley do you mind if I add some tests for prettyprinting? That would mean we'd have to update those files when prettyprinting is changed, but it would make it easier to see different scenarios.

**Comment by jwiegley** [comment]
@domenkozar I'd love it.

**Pull request merged**
