### PR TITLE
Test with Travis

### PR DESCRIPTION
**Pull request by vaibhavsagar**
It's likely that there is a good reason this hasn't already been implemented, but this was a simple change so I thought I'd submit a PR regardless.

### CODE REVIEW

**Comment by jwiegley** [comment]
Thanks!

**Comment by vaibhavsagar** [comment]
My pleasure!

**Comment by vaibhavsagar** [comment]
If you want to enable this you'll need a Travis CI account and the repository to be switched on under https://travis-ci.org/profile/jwiegley.

**Comment by jwiegley** [comment]
Done.

**Comment by vaibhavsagar** [comment]
Thanks again!

**Pull request merged**
