### PR TITLE
Clean up hashing-related dependencies

### PR DESCRIPTION
**Pull request by sjakobi**
Background: https://github.com/haskell-nix/hnix/issues/588#issuecomment-634692400

### CODE REVIEW

**Comment by sjakobi** [comment]
Travis looks green: https://travis-ci.org/github/haskell-nix/hnix/builds/691790916

No idea why the status isn't being updated here…

**Review by sorki — APPROVED** [review]
:+1: `-52` :heart: After #583 as well I think. I might try testing this with `ghcjs` since I have it built with lots of deps for another project.

**Comment by sorki** [comment]
Regarding check results, I've read few reports about Travis being rate limited by GitHub so it can happen. I really hope it's not done intentionally to get people to use actions.

**Comment by sjakobi** [comment]
Thanks for the review @sorki!

FWIW, I believe that this doesn't actually cause any change in behaviour, not even regarding the preference of `cryptohash-*` vs. `hashing`, since the old code seemed to default to `hashing` anyway.

**Comment by Anton-Latukha** [comment]
Oh, so that is why it always building.

Yep. Project was stale and had low profile quotas. Then badges. Then in CI dev (>100 Travis triggers => >500 separate builds) - I probably hit over and above many quotas, so they/system reacted timing-out our project due to anomaly, it is strange that it happened to this PR and not to CI PR.

I restarted the most recent build of this PR.

**Comment by Anton-Latukha** [comment]
:+1:

**Comment by Anton-Latukha** [comment]
Just a seconds before me 8)

**Comment by sjakobi** [comment]
CI seems pretty quick BTW, @Anton-Latukha! :+1:

**Comment by Anton-Latukha** [comment]
it is because Travis also caching stuff.

Travis cache is far from ideal, but it is near and so fast cache in the datacenter through some fiber channel, then downloading it from remote Cachix.
Travis cache can miss, since Nix hierarchy built on unique deterministic packages and their cache was not built for that design, but Cachix would preserve the useful Nix packages always. It seems a great combination.

**Pull request merged**
