### PR TITLE
WIP: Annotate expressions with their location

### PR DESCRIPTION
**Pull request by expipiplus1**
Some initial work towards fixing #33 

This is far from complete, Some functions need implementing, and there's some tidying up to do in the parser. `Annotation.hs` could also use a little more organisation.

It typechecks though :)

### CODE REVIEW

**Comment by jwiegley** [comment]
@expipiplus1 Nice! If this is a work in progress, shouldn't I wait until you're done?

**Comment by expipiplus1** [comment]
Yes! Please don't merge now!

**Comment by expipiplus1** [comment]
@jwiegley How would you suggest dealing with whitespace in the expression annotations?

It's not possible to eat the whitespace before recording the start of the span as some parsers are whitespace sensitive (the tests fail for `select`).

There isn't any opportunity to record trailing whitespace, as `token` eats any trailing whitespace.

The best option I can think of is to postprocess the source spans to remove leading and trailing whitespace.

Another option would be to split the parser and the lexer, but that'd probably be a much larger job.

Another option would be to leave it as is, and let the user deal with it :)

**Comment by jwiegley** [comment]
For now we can let the user deal with it, but I like the idea of splitting parser and lexer.

**Comment by expipiplus1** [comment]
The annoying thing is that _I'm_ the user at the moment :)

If I find a tidy way of stripping whitespace I think I'll do that.

**Comment by expipiplus1** [comment]
Another possibility would be to modify the definition of whitespace so that it maintains some kind of `beforeWhitespacePos` + `afterWhitespacePos` state. I'm not sure if this is possible in a Trifecta parser though. Does this idea makes sense?

**Comment by expipiplus1** [comment]
This is working well enough now for me to have made this little utility to automatically update `fetchgit` values in nix expressions to the latest versions.

https://github.com/expipiplus1/update-nix-fetchgit

**Comment by expipiplus1** [comment]
@jwiegley aside from some tests and documentation, is there anything major preventing this from being merged

**Pull request merged**
