### PR TITLE
Add QuickCheck test for pretty printer and parser

### PR DESCRIPTION
**Pull request by mpickering**
I have not analysed any of the failures or attempted to refine the
generator.

This would be an easy place for a new contributor to start by refining the generator and looking at why the tests are failing.

See #158

### CODE REVIEW

**Comment by jwiegley** [comment]
The test is currently failing...

**Comment by jwiegley** [comment]
@mpickering Can you fix the broken test so I can merge this wonderful work? Thanks!

**Comment by mpickering** [comment]
Fixing the broken test involves fixing the pretty printer and parser which I don't have time to commit to right now.

**Comment by jwiegley** [comment]
@mpickering Ah, understood, how much time do you estimate it to be, and what difficulty?

**Comment by mpickering** [comment]
I didn't begin to look yet why it is failing. Perhaps at the weekend I will get the chance.

**Comment by mpickering** [comment]
@jwiegley The test passes now with some refinement and two bug fixes.

**Comment by jwiegley** [comment]
@mpickering I've had to disable these tests for the time being, until we've run through a lot more examples. The very first run on Travis broke, and I'm afraid that having it enabled will prevent CI from working until we've ironed out some of these issues.

The error can be seen with:

    hnix-tests --quickcheck-replay=678297

**Comment by jwiegley** [comment]
@mpickering I've converted your tests to use Hedgehog rather than QuickCheck, since it gives us better shrinking for free.

**Pull request merged**
