### PR TITLE
Distinguish between the three different types of string coercion

### PR DESCRIPTION
**Pull request by jwiegley**

### CODE REVIEW

**Comment by jwiegley** [comment]
@shlevy @gbwey9 This code isn't quite working yet, but should be developed in tandom with the string context work, I think. @gbwey9 Do you want to take this code over from here?

**Comment by gbwey9** [comment]
Yes, I'll get to work on this one.

**Comment by shlevy** [comment]
Yeah, this is a natural consequence of getting string context right.

**Comment by jwiegley** [comment]
This will be obviated by other work coming in soon from @shlevy.

**Pull request closed without merging**
