### PR TITLE
travis: download cachix with smaller closure, pin nixpkgs

### PR DESCRIPTION
**Pull request by domenkozar**
- strict was removed as it's not needed anymore
- cachix in nixpkgs has significantly smaller closure as of last month
- pin nixpkgs to ensure reproducability

### CODE REVIEW

**Comment by domenkozar** [comment]
@jwiegley this is ready :)

**Comment by jwiegley** [comment]
@domenkozar Why is strict no longer needed? We want to make sure that warnings don't creep into the CI build.

**Comment by domenkozar** [comment]
@jwiegley https://github.com/dezgeg/nixpkgs/commit/f3758258b8895508475caf83e92bfb236a27ceb9 was merged to nixpkgs master, which reduces the GCC cli line and thus GHC doesn't fail with `argument list too long`.

If that's the warning you're talking about, this should be fixed.

**Comment by matthewbauer** [comment]
@domenkozar I think there is some confusion here. What you are referring to is ```strictDeps``` which is not implemented in hnix. This STRICT flag just controls whether to evaluate strictly or lazily.

**Comment by domenkozar** [comment]
Oh, I assumed that it's strictDeps yes, I see now that it means -Werror. Reverting.

**Comment by domenkozar** [comment]
@matthewbauer thanks for clarifying my slip, I've pushed changes to exclude that.

**Comment by jwiegley** [comment]
Actually `STRICT` just controls whether we compile with `-Wall` or not; it doesn't affect the semantics of evaluation at all.

**Pull request merged**
