### PR TITLE
Fix eval-fail-undeclared-arg

### PR DESCRIPTION
**Pull request by ryantrinkle**

### CODE REVIEW

**Comment by jwiegley** [comment]
Nice!

**Comment by domenkozar** [comment]
Shouldn't this come with a test? :)

**Comment by ryantrinkle** [comment]
@domenkozar You can run the tests by doing `LANGUAGE_TESTS=yes cabal test`, including eval-fail-undeclared-arg :)

**Comment by domenkozar** [comment]
Oh, so this fixed the tests? Missed that :)

**Comment by jwiegley** [comment]
It fixed one of the language tests.  Still 63 broken.

**Pull request merged**
