### PR TITLE
Add tests for lessThan and remove hacky call

### PR DESCRIPTION
**Pull request by emmanueldenloye**
Closes issue #438

### CODE REVIEW

**Review by shlevy — DISMISSED** [review]

**Comment by jwiegley** [comment]
Did you mean to commit an empty `cabal.project.local`, and to change the `data/nix` submodule?

**Comment by emmanueldenloye** [comment]
@jwiegley I must have missed that. Should I just put that file in the .gitignore file or just simply delete it?

**Comment by jwiegley** [comment]
We can add it to `.gitignore`.

**Comment by jwiegley** [comment]
You removed all of your code other than the two problem items. So, just reverse that. :)

**Review by jwiegley — CHANGES_REQUESTED** [review]
This PR is now effectively empty...

**Comment by emmanueldenloye** [comment]
I am going to delete it and create another one. I want to put my code on a separate branch entirely. This is so I can have multiple PRs open. I mistakenly opened this PR on the master branch. My bad!

**Comment by emmanueldenloye** [comment]
Closing branch!

**Pull request closed without merging**
