### PR TITLE
Proposing the logo

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Thought about it for quite some time, and had a pretty balanced idea for the project logo.

Kept it locally for a month, and then thought why I do it, when our team opinion is needed.

Why logo? - At some decisive point in the future we may need to have the distinctive logo for the migration movement. Lets lay it and forget the logos exists until the situation would sway in our favor and we would need to push the transition button.

Images presented here:
  * Full variant: https://raw.githubusercontent.com/Anton-Latukha/hnix/072628a8623cf63f43e03fb0bb8e9b29127e40c8/doc/images/HNix.svg
  * Small variant: https://raw.githubusercontent.com/Anton-Latukha/hnix/072628a8623cf63f43e03fb0bb8e9b29127e40c8/doc/images/HNixSmall.svg

Also requesting directly @jwiegley, the author's opinion.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
If would be required - I can provide a list of design ideas behind this logo.

**Comment by sjakobi** [comment]
The swirl reminds me of the Debian logo: https://www.debian.org/logos/

**Comment by Anton-Latukha** [comment]
Yes, that is one of the ideas. Debian is a swirl, Suse has famous lizard tail swirl, Nix is a swirl - it is a message that HNix is about software distribution. And Debian and Suse and Nix are a good logos theme to be in line and association with.

**Comment by Anton-Latukha** [comment]
If there is need to explicitly relicense it, or sign-off rights to it - ready to do so.

**Comment by jwiegley** [comment]
I like it @Anton-Latukha! Reminds me of the whirlpool in Ultima III. :-)

**Comment by Anton-Latukha** [comment]
_offtopic_: @jwiegley That is too much of a reference to address... Talking about times, well, some of my first memories is father soldering and launching the ZX Spectrum 48K © 1982 Sinclair Research Ltd... early on I figured-out that GOTOs are not the way at all, that computer that pretty much shaped me.

Me learning Haskell can be observed as a kid that tries to free from the internal stigma of BASIC programmer I received, to prove that the same kid that was formed by BASIC can become a Haskell programmer, and by learning Haskell, pretty much fights traumas and terrors of a rough childhood and lost beliefs in himself, to prove himself, feel and understand that he still can program easily and reconnect with creativity. I have almost infinite impostor syndrome, which I always need to overcome to sit and program anything, so I often pretend that I do not program, that I configure machines.

---

Thank you everybody for review and giving a pass on this.

**Pull request merged**
