### PR TITLE
Allow prettyprinter-1.4.0

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
One test failed when I ran the testsuite with `cabal test`:

```
Test suite hnix-tests: RUNNING...
error: undefined variable 'getContext' at /home/simon/src/hnix/tests/eval-compare/builtins.getContext.nix:3:4
hnix
  Eval comparison tests
    builtins.getContext.nix:                                         FAIL
      Exception: readCreateProcess: nix-instantiate "--eval" "--strict" "tests/eval-compare/builtins.getContext.nix" (exit 1): failed

1 out of 265 tests failed (1.48s)
```

I suspect that this isn't related to the prettyprinter update.

**Comment by sjakobi** [comment]
> One test failed when I ran the testsuite with `cabal test`:

It's probably because I didn't run the tests in `nix-shell`. When I try that, `/nix` attempts to eat all my disk space… :/

**Comment by sjakobi** [comment]
Thanks for the merge! :)

Could you possibly make a release? Since support for GHC-8.8 seems to be so tricky, I'm not sure whether it's worth waiting for it.

**Comment by jwiegley** [comment]
if it's just for the bounds, how about we just update the .cabal file?

**Comment by sjakobi** [comment]
> if it's just for the bounds, how about we just update the .cabal file?

That should be good enough for my needs.

**Comment by jwiegley** [comment]
Looks like I need to cut a point release, but I'm not able to get the hnix to build to work here, which is strange. Does `nix-build` work for you in the current master?

**Comment by sjakobi** [comment]
> Does `nix-build` work for you in the current master?

No, it ends up failing due to `parser-combinators` missing?!

<details>

```
building '/nix/store/yvr1c2zqbri3mh52vj160j9jxfkb17v3-hnix-0.6.1.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/745d4rlrmrj61kkbbbvcfs9rxlkxlqm6-ghc-8.6.4.
unpacking sources
unpacking source archive /nix/store/kfymg3w36hcacjy1kjasnhm6gwqnwjx5-hnix
source root is hnix
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/pjadwqnng2ipdmychhdzbrhsyai29hj4-hnix-0.6.1 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/5g1kxaivpm3jfg2gdpvnil927kknx6sx-hnix-0.6.1-doc/share/doc/hnix-0.6.1 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-option=-j4 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/vwcrxiwxr294b7iargxcqbda0nr89vfn-ncurses-6.1-20190112/lib --extra-lib-dirs=/nix/store/8pivgdaciz2add2wv7ff13gbz0rijs3f-libffi-3.2.1/lib --extra-lib-dirs=/nix/store/yq9lngyw980m5xdavkzb275xp50nx4my-gmp-6.1.2/lib --extra-lib-dirs=/nix/store/vwcrxiwxr294b7iargxcqbda0nr89vfn-ncurses-6.1-20190112/lib --extra-include-dirs=/nix/store/la7djd5329x88mnrmky2hxl7f6g4g8wn-nix-2.3pre6895_84de821-dev/include --extra-lib-dirs=/nix/store/la7djd5329x88mnrmky2hxl7f6g4g8wn-nix-2.3pre6895_84de821-dev/lib --extra-include-dirs=/nix/store/i9wjrkcg7g5y6p6g6w6xkwsxy8rd4ck7-boehm-gc-8.0.4-dev/include --extra-lib-dirs=/nix/store/i9wjrkcg7g5y6p6g6w6xkwsxy8rd4ck7-boehm-gc-8.0.4-dev/lib --extra-lib-dirs=/nix/store/p6y0fw99xrsma97h209ci70dq0amwck0-boehm-gc-8.0.4/lib --extra-lib-dirs=/nix/store/i6h9jxibxf6faamjjmrqnig3mhkzvvy1-nix-2.3pre6895_84de821/lib
Using Parsec parser
Configuring hnix-0.6.1...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
parser-combinators >=1.0.1 && <1.1 || >=1.2.0 && <1.3

builder for '/nix/store/yvr1c2zqbri3mh52vj160j9jxfkb17v3-hnix-0.6.1.drv' failed with exit code 1
error: build of '/nix/store/yvr1c2zqbri3mh52vj160j9jxfkb17v3-hnix-0.6.1.drv' failed
```
</details>

**Comment by sjakobi** [comment]
I think this might be related to this overlay(?) which points at [`parser-combinators-0.4.0`](https://github.com/mrkkrp/parser-combinators/commit/dd6599224fe7eb224477ef8e9269602fb6b79fe0):

https://github.com/haskell-nix/hnix/blob/2df4986aa6b10aa741400bca1ed595fa2fea1b13/ghcjs/default.nix#L46-L51

If I extend the version constraint on `parser-combinators` to allow v0.4.0, `nix-build` succeeds.

https://github.com/haskell-nix/hnix/blob/2df4986aa6b10aa741400bca1ed595fa2fea1b13/hnix.cabal#L519

**Comment by sjakobi** [comment]
> I think this might be related to this overlay(?) which points at [`parser-combinators-0.4.0`](https://github.com/mrkkrp/parser-combinators/commit/dd6599224fe7eb224477ef8e9269602fb6b79fe0):

Ah no, that's not it. `nix-build` seems to build `parser-combinators-1.1.0` which doesn't match the above constraint that excludes any `1.1.*` version. I'll make a PR to allow `1.1.*` too.

**Pull request merged**
