### PR TITLE
Switch to prettyprinter library from ansi-wl-pprint

### LINKED ISSUE #379: Switch from ansi-wl-pprint to prettyprint
https://github.com/quchen/prettyprinter It seems better. See also https://github.com/ekmett/ansi-wl-pprint/issues/18 which shows progress in deprecating the first.

### PR DESCRIPTION
**Pull request by Ericson2314**
Closes #379

### CODE REVIEW

**Comment by jwiegley** [comment]
Can you resolve conflicts and repush? I'll merge this in next.

**Comment by Ericson2314** [comment]
Passed https://hydra.reflex-frp.org/jobset/hnix/hnix-pr-388/evals too

**Comment by Profpatsch** [comment]
This is a breaking change to the API, so next release has to be `0.6`.

**Comment by jwiegley** [comment]
We intend to release this next weekend (9/10).

**Pull request merged**
