### PR TITLE
Bump bounds for regex-tdfa, semialign and semialign-indexed

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
I've built this locally with GHC-8.6.5.

**Comment by jwiegley** [comment]
@sjakobi With GHC 8.6.5 I get this:

```
builder for '/nix/store/y7zw3ff084xmdc61x96q9ci0cd6vzyda-semialign-indexed-1.1.drv' failed with exit code 1; last 10 log lines:
      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  src/Data/Semialign/Indexed.hs:112:10: error:
      • No instance for (Zip Vector)
          arising from the superclasses of an instance declaration
      • In the instance declaration for ‘ZipWithIndex Int Vector’
      |
  112 | instance ZipWithIndex Int Vector where
      |          ^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by sjakobi** [comment]
@jwiegley That's strange. Could it be that you're building with `semialign-1` which doesn't have the `Zip Vector` instance?

`semialign-indexed-1.1` has a constraint `semialign == 1.1.*` that should prevent this though…

**Comment by jwiegley** [comment]
Found it, I needed to override to use `semialign_1_1`.

**Pull request merged**
