### PR TITLE
Replace hashing by cryptonite

### PR DESCRIPTION
**Pull request by sboehler**
ZuriHac project in order to get hnix on stackage

### CODE REVIEW

**Comment by flokli** [comment]
This helps towards #494.

**Comment by vaibhavsagar** [comment]
This definitely won't work with GHCJS. Is that an issue?

**Comment by sboehler** [comment]
> This definitely won't work with GHCJS. Is that an issue?

I cannot judge on that. But what is the issue with cryptonite and GHCJS?

The alternative approach would be to get hashing itself into stackage.

**Comment by ryantrinkle** [comment]
I'd definitely prefer to keep GHCJS working.

**Comment by vaibhavsagar** [comment]
@sboehler see https://github.com/haskell-crypto/cryptonite/issues/243#issuecomment-421006819.

**Comment by sboehler** [comment]
If hnix is to preserve GHCJS compatibility and get into stackage, some dependencies (like hashing and monadlist) need to be added to stackage.

Closing this for now.

**Comment by flokli** [comment]
I guess GHCJS in general isn't a requirement, but being able to run some version of hnix in the browser, like in [A tour of Nix](https://nixcloud.io/tour/?id=1) is a very useful usecase we shouldn't break easily.

Another possible target to run this on might be webassembly, but I guess it'll also take quite some time until we can get haskell libs with c bindings (like cryptonite) compiled to that platform (see https://github.com/tweag/asterius/issues/148 for some pointers). That left aside, getting crypto done safely in haskell and randomness into webassembly are two other problems.

That being said, getting a pure haskell hasing library into stackage and using that looks like the easiest way forward, at least for now.

**Pull request closed without merging**
