### PR TITLE
Add builtins.split

### PR DESCRIPTION
**Pull request by mightybyte**

### CODE REVIEW

**Comment by jwiegley** [comment]
I'd like to avoid a dependency on `directory`, since we already depend on `unix`.

**Comment by jwiegley** [comment]
Actually, never mind that, they don't have an implementation of `canonicalizePath`

**Comment by jwiegley** [comment]
@mightybyte Is this close to being ready?

**Comment by mightybyte** [comment]
The split implementation is ready but it's still not passing yet because there's one test that includes an indented string and that's not working yet.

**Comment by jwiegley** [comment]
Ah, since there's already an issue for that, we shouldn't hold up your split work. The scope of the PR just needs to be narrowed down to just the changes needed for split.

**Comment by mightybyte** [comment]
Ok, then this should be ready.  It still won't pass the test case unless you comment out the one with the indented text.

**Comment by jwiegley** [comment]
Merged by hand.

**Pull request closed without merging**
