### PR TITLE
Fix since annotation

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Good. Missed that one.

So `0.10.1.1` then.

**Comment by Anton-Latukha** [comment]
`0.10.1.1` then.

**Comment by sjakobi** [comment]
@Anton-Latukha There's no need to make a release just for this minor docs fix.

**Comment by Anton-Latukha** [comment]
Well, Ok.

It may be strange that Haddock does not show recent instances thou.

**Comment by Anton-Latukha** [comment]
:sweat_drops: Just wanted to make an ideal release.

**Pull request merged**
