### PR TITLE
Use haskeline-0.8

### PR DESCRIPTION
**Pull request by sjakobi**
The MonadException class was removed in favor of MonadCatch, so we
can remove its instances.

### CODE REVIEW

**Comment by sjakobi** [comment]
This broke the build with Nix:

```
Setup: Encountered missing dependencies:
haskeline >=0.8.0.0 && <0.9
```

How do I tell Nix to use `haskeline-0.8.0.0` and `repline-0.3.0.0`?

**Comment by sjakobi** [comment]
I have added some changes to fix the REPL build (with `cabal` and GHC 8.6.5). Note that I've never used the REPL though, so I'm not sure whether it still works as expected.

**Comment by sorki** [comment]
> This broke the build with Nix:
> 
> ```
> Setup: Encountered missing dependencies:
> haskeline >=0.8.0.0 && <0.9
> ```
> 
> How do I tell Nix to use `haskeline-0.8.0.0` and `repline-0.3.0.0`?

One option is to use `source-overrides` which is supported by `developPackage` 

```
--- a/default.nix
+++ b/default.nix
@@ -129,6 +129,11 @@ in haskellPackages.developPackage {
   name = "hnix";
   root = ./.;
 
+  source-overrides = {
+    haskeline = "0.8.0.0";
+    repline = "0.3.0.0";
+  };
+
   modifier = drv: pkgs.haskell.lib.overrideCabal drv (attrs: {
```

Which for me results in
```
haskeline-tests: which: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite haskeline-tests: FAIL
```
as it just builds the package from hackage but `nixpkgs` might contain another fixes for it to build.

Another option is to add an overlay item calling `callHackage` or (`callCabal2nix` + git repo) for both packages iff needed.

Edit: forgot to add another one which is to use pinned `nixpkgs` and `pkgs.haskell.packages.ghcXYZ` which contains the versions you're interested in.

**Comment by sjakobi** [comment]
I'm pleasantly surprised that [CI is green](https://travis-ci.org/github/haskell-nix/hnix/builds/691786595) now, although the GitHub status doesn't show it.

**Comment by sjakobi** [comment]
Thanks for the hints @sorki! I haven't tried any of them yet though, since it seems that disabling the executable might just be good enough.

What do you think?

**Review by sorki — DISMISSED** [review]
LGTM, Thanks! We might want to wait for #583 just to be sure.

**Comment by sjakobi** [comment]
The GHC 8.10 build is currently broken here (https://travis-ci.org/github/haskell-nix/hnix/jobs/692761966), but https://github.com/haskell-nix/hnix/pull/597 should take care of that.

**Comment by sjakobi** [comment]
Resolving merge conflicts via the web interface seems to dismiss any approvals, so I'll need another one now. :)

**Review by Anton-Latukha — APPROVED** [review]

**Comment by Anton-Latukha** [comment]
The CI config here in PR didn't renewed, https://travis-ci.org/github/haskell-nix/hnix/builds/692767228

It couldn't build with the GHC 8.10.

**Comment by Anton-Latukha** [comment]
@sjakobi seems there also was an internal branch: https://github.com/haskell-nix/hnix/tree/haskeline-0.8

**Comment by sjakobi** [comment]
Thanks, I had pushed that one to the wrong remote. It's deleted now.

**Pull request merged**
