### PR TITLE
Bump minimum supported version to GHC 8.4.4

### PR DESCRIPTION
**Pull request by jwiegley**
This involved:

  - Changing `default.nix`
  - Changing `.travis.yml`
  - Remove a lot of unnecessary imports, to fix warnings.

### CODE REVIEW

**Review by mightybyte — APPROVED** [review]
Looks good to me if it passes CI.

**Comment by jwiegley** [comment]
@mightybyte CI broke because `ghc844` requires a newer nixpkgs. I'm going to try pinning to `nixos-18.09`.

**Comment by vaibhavsagar** [comment]
I don't think `nixos-18.09` has `8.4.4`, but I could be wrong.

**Comment by jwiegley** [comment]
@vaibhavsagar https://github.com/NixOS/nixpkgs/blob/release-18.09/pkgs/top-level/haskell-packages.nix seems to indicate that it's there.

**Comment by domenkozar** [comment]
I ported it a couple of days ago (and also 8.6.2)

**Comment by jwiegley** [comment]
@domenkozar OK, so ditch this PR?

**Comment by jwiegley** [comment]
I take it all the warnings have been resolved for 8.6.2?

**Comment by domenkozar** [comment]
The main caveat for GHC 8.6.2 is that it's going to be hard to use nixpkgs haskell set, as it hasn't been updated yet to match stackage nightly. I suggest we stay on GHC 8.4.4 until LTS-13 is released (hopefully in less than a month).

Otherwise my GHC 8.6 branch compiles. I could CPP it so we can supporot 8.4/8.6

**Comment by jwiegley** [comment]
Ok, then I just need to update `cachix` for this to pass CI on Travis.

**Pull request merged**
