### PR TITLE
accommodate with store's new addToStore API

### PR DESCRIPTION
**Pull request by soulomoon**
bump up hnix-store-remote and hnix-store-core to 0.7.0
Api change due to https://github.com/haskell-nix/hnix-store/pull/177
It also serves as base point to #1051

### CODE REVIEW

**Comment by soulomoon** [comment]
It should fix #1076

**Comment by soulomoon** [comment]
I don't know why Optional checks failed. Maybe some one could help to review it

**Comment by sjakobi** [comment]
> I don't know why Optional checks failed.

It seems that the failing jobs are based on the `nixos-unstable` channel which currently contains `hnix-store-core-0.5.0.0` and `hnix-store-remote-0.5.0.0`.

https://github.com/haskell-nix/hnix/blob/83ffe984635144ee8add44a4ea988c1867d5bad1/.github/workflows/Optional-Nix-dev-env-main.yml#L73

https://github.com/haskell-nix/hnix/blob/83ffe984635144ee8add44a4ea988c1867d5bad1/.github/workflows/Optional-Nix-dev-env-main.yml#L97

(Note that the job named `Default Nixpkgs GHC (8.10), strict quality build, SDist, Optimizations, Benchmark, Haddock, Completions` [actually uses GHC-9.0.2](https://github.com/haskell-nix/hnix/runs/7933619183?check_suite_focus=true#step:5:718)!)

IMHO ignored CI failures have a bad signal-to-noise ratio, and I wouldn't mind if they would be removed.

**Comment by soulomoon** [comment]
Thanks for the help @sjakobi  
I am able to work it out now.
It seems the build script specifies the pkgs version separately.
And in the current rev for pkgs, hnix-store is not up to date.
Bumped up rev for pkgs, everything works again now.
Also I add ghc version to githubflow script to make 8.10 stays in ghc8107

**Pull request merged**
