### PR TITLE
Dockerfile: update

### PR DESCRIPTION
**Pull request by vaibhavsagar**
Refs #491.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Hmm, this doesn't seem to work. I keep getting this error:

```
building '/nix/store/9ll0mifwwr2vxh1zkhqgnarwjgmxg4gn-cabal2nix-hnix.drv'...
installing
error: opening lock file '/nix/var/nix/db/big-lock': Permission denied
error: opening lock file '/nix/var/nix/db/big-lock': Permission denied
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
cabal2nix: user error (Failed to fetch source. Does this source exist? Source {sourceUrl = "/nix/store/icml732qzxsp88qbsr0b7ab21pilvvhq-build", sourceRevision = "", sourceHash = Guess "", sourceCabalDir = ""})
builder for '/nix/store/9ll0mifwwr2vxh1zkhqgnarwjgmxg4gn-cabal2nix-hnix.drv' failed with exit code 1
```

**Comment by jwiegley** [comment]
Is this PR ready to go yet @vaibhavsagar?

**Comment by vaibhavsagar** [comment]
No, I'm still getting the same error. I think IFD is to blame but I'm not sure. Can you try? It might be something silly that I'm doing.

**Comment by Ericson2314** [comment]
I would just drop Docker, TBH. There shouldn't be hnix-specific about this, vs putting an arbitrary haskell executable in a docker image, right?

**Comment by Anton-Latukha** [comment]
1. `Dockefile`s and their images can be imported in many container specification implementations. Which have are name *plethora*, now.
  For example, `Dockefile` can be imported or directly converted into the Kubernetes configuration.
2. It is a good idea in the container to make a [standalone static binary](https://github.com/nh2/static-haskell-nix), like was [covered on the last NixCon](https://www.youtube.com/watch?v=7hQOiut_MiA).
  Containers&container DevOps'es love static binaries for more lean and trouble-free experience, than a big containers. Which makes `hnix` *AFAIU* a good root to populate some container, if you happen to want/need `hnix` in a container.
3. Also `Dockefile` is good reference documentation on how one sets-up/integrates **this* in the container. Even if the documentation is long, unclear, or not present. Back in time sometimes I preferred to find a good `Dockerfile` to use/look how to set **this* up in a container.

**Comment by jwiegley** [comment]
Dockerfile has been removed.

**Pull request closed without merging**
