### PR TITLE
Add builtins.hasContext

### PR DESCRIPTION
**Pull request by rpglover64**
#234 

I would like to write a test for this, but I can't figure out how to generate a value which should have a context.

### CODE REVIEW

**Comment by rpglover64** [comment]
Does not work properly.

**Comment by rpglover64** [comment]
To be fair, I'm not sure that the context is being constructed properly the code that checks it is pretty simple. Here's the worrying example:

```
[nix-shell:~/Documents/Haskell/hnix]$ ./dist/build/hnix/hnix --eval --expr 'let lib = (import <nixpkgs/lib>); pkg = import <nixpkgs> {}; in builtins.hasContext (baseNameOf "${./data/nix/tests/lang/eval-okay-context.nix}") '
false

[nix-shell:~/Documents/Haskell/hnix]$ nix-instantiate --eval --expr 'let lib = (import <nixpkgs/lib>); pkg = import <nixpkgs> {}; in builtins.hasContext (baseNameOf "${./data/nix/tests/lang/eval-okay-context.nix}") '
true
```

However, when I put in some debug-trace statements, the string passed to `builtins.hasContext` seems to have an empty context.

Reopening since the problem appears to be elsewhere.

**Comment by shlevy** [comment]
Hoping to work with @gbwey9 on fixing up context handling today.

**Comment by shlevy** [comment]
(the logic here seems right to me though)

**Comment by jwiegley** [comment]
@shlevy Rather than create a new label to associate this issue with a "project", let's try creating a GitHub project! I've never used those before, and would love to give it a try.

**Comment by jwiegley** [comment]
Merged manually.

**Pull request closed without merging**
