### PR TITLE
CI: Travis: upd: make GHC 8.10 mandatory, since it passes build in CI

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Relates to Report: #592 

We got a successful CI build of GHC 8.10!

Let us stabilize on it, and make further checks and accordance of us to the newest compiler mandatory.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
@sjakobi I see you active, please, lets make GHC 8.10 mandatory.

**Comment by sjakobi** [comment]
If builds with GHC 8.10 pass already, that suggests that the `hnix` executable isn't being built. (I think you have already commented to a similar effect.) Any idea why we aren't building the executable?

**Review by sjakobi — DISMISSED** [review]
Awesome! :)

**Comment by Anton-Latukha** [comment]
> If builds with GHC 8.10 pass already, that suggests that the `hnix` executable isn't being built. (I think you have already commented to a similar effect.) Any idea why we aren't building the executable?

Yep, there is #584.

The obvious reason - it is homehow out of the `src/` tree, it seems probable that John took some older basics code of other people and started from it, and moved stuff into `src/`. `main/` seems very old and very unmaintained code.

Maybe stuff in `main/`does not compile and runs just as a Haskell script.

Cabal is the key, CI would help, enabling of the packaging should reveal issues that would explain why they not getting into instructions for Nix.

**Comment by Anton-Latukha** [comment]
Bummer, now `lens-family-th-0.5.0.2` broken in `nixpkgs-unstable` (virtually funny flipping the table 8) ).

**Comment by Anton-Latukha** [comment]
There is a lot of problems with Haskell in Nixpkgs popping up, due to the ecosystem still relying on Cabal and Stack, so they do not tend to see the problems and inconsistencies that arise in pure Nix builds from Cabal & Hackage changes.

**Comment by Anton-Latukha** [comment]
Now it compiles again :thinking:

**Comment by Anton-Latukha** [comment]
Closing since #604

**Pull request closed without merging**
